## Append samples of your project ##
resources:
- v1alpha1_lastpass.yaml
- v1alpha1_lastpassgroup.yaml
# - _v1alpha1_lastpassgroup.yaml
- v1alpha1_lastpasscustom.yaml
# - _v1alpha1_lastpasscustom.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
